name: DtoN App deploy
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: npm
          cache-dependency-path: ./hello-world
      - uses: aws-actions/setup-sam@v2
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1
      - name: Build DtoN App
        run: sam build --use-container
      - name: Deploy DtoN App
        env:
          DISCORD_API_TOKEN: ${{ secrets.DISCORD_API_TOKEN }}
          NOTION_API_KEY: ${{ secrets.NOTION_API_KEY }}
          LAMDA_ROLE: ${{ secrets.LAMDA_ROLE }}
        run: sam deploy \
          --no-confirm-changeset \
          --no-fail-on-empty-changeset \
          --parameter-overrides \
          ParameterKey=DiscordApiToken,ParameterValue=$DISCORD_API_TOKEN \
          ParameterKey=NotionApiKey,ParameterValue=$NOTION_API_KEY \
          ParameterKey=LamdaRole,ParameterValue=$LAMDA_ROLE
